### ISSUE TITLE
rm errors when unsetting

### ISSUE THREAD

**Issue by chgad** [mimischi/dokku-dockerfile#3]
When Unsetting a dockerfile path it produces a "wall of errors" as shown here 
![image](https://user-images.githubusercontent.com/21121667/35097642-4e1dcb5a-fc51-11e7-8a0f-830745eee36a.png). It seems to only effect the cache/ directory. 

it would be nice to either not see this, or to solves this.

**Comment by mimischi** [comment]
Solved #5.
